Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medic.Controllers
{
    [AllowAnonymous]
    public class AboutUsController : Controller
    {
        // GET: AboutUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/BlogController.cs
using Medic.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace Medic.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        private ApplicationDbContext context;
        public BlogController()
        {
            context = new ApplicationDbContext();
        }
        public ActionResult Index()
        {
            return View();
        }

       
        [System.Web.Http.HttpPost]
        public ActionResult PostUser(Post pst)
        {
            if (ModelState.IsValid)
            {

                try
                {

                    bool td = string.IsNullOrEmpty(pst.post);

                   /* if (!string.IsNullOrEmpty(pst.post))
                    {
                        return Json(new { status = "Please Write Something.." });
                    } */

                    string currentUserId = User.Identity.GetUserId();

                 //   Post obj = new Post();
                    var obj = new Post
                    {
                        post = pst.post,
                        postDate = DateTime.Now,
                        UserId = currentUserId
                    };


                     context.Posts.Add(obj);
                     context.SaveChanges();

                    return Json(new { status = "DATA SAVED SUCCESSFULLY" });
                }
                catch (Exception e)
                {
                    return Json(new { status = "PROBLEM OCCURED " + e });
                }

            }
            else
            {
                return Json(new { status = "INVALID" });
            }
        }

        [System.Web.Http.Route("ShowAllPost")]
        [System.Web.Http.HttpGet]
        public  Object ShowAllPost()
        {
            var list =  context.Posts.ToList(); ;
            var x = 10;

            return list;
        }

        [System.Web.Http.Route("GetUsers")]
        [System.Web.Http.HttpGet]
        public async Task<ActionResult> GetUsers()
        {
            return Json(await context.Posts.ToListAsync());
        }

        [System.Web.Http.Route("ShowAllPost2")]
        [System.Web.Http.HttpGet]

        public int ShowAllPost2()
        {
            var list = context.Posts.ToList();
            var x = 10;
            // var obj = new { list = list };
            return Ok(1);


        }

        private int Ok(int v)
        {
            throw new NotImplementedException();
        }

        [System.Web.Http.Route("ShowAllPost3")]
        [System.Web.Http.HttpGet]
        public JsonResult ShowAllPost3()
        {
            var list = context.Posts.ToList();
            var x = 10;
            // var obj = new { list = list };

            return Json(new { success = "Succes from server" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/RoleController.cs
using Medic.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Medic.Controllers
{
    [AllowAnonymous]
    public class RoleController : Controller
    {
        private ApplicationRoleManager _roleManager;
        public RoleController()
        {
        }

        public RoleController(ApplicationRoleManager roleManager)
        {
            RoleManager = roleManager;
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        // GET: Role
        public ActionResult Index()
        {
            List<RoleViewModel> list = new List<RoleViewModel>();
            foreach (var role in RoleManager.Roles)
                list.Add(new RoleViewModel(role));
            return View(list);
        }
        public ActionResult Create()
        {
            return View();   
        }
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            var role = new ApplicationRole() { Name = model.Name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }
        [HttpPost]
        public async Task<ActionResult> Edit(RoleViewModel model)
        {
            var role = new ApplicationRole() { Id = model.Id,Name=model.Name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Details(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }
        public async Task<ActionResult> Delete(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medic.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Department()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div>
        @RenderBody()
        <hr />
        @Html.Partial("_footer")
    </div>
    <script src="~/Scripts/Home/React/dist/bundle.js"></script>

    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
    @RenderSection("reactScript", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<header>
    <div class="header-area ">
        <div class="header-top_area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-md-6 ">
                        <div class="social_media_links">
                            <a href="#">
                                <i class="fa fa-linkedin"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a href="#">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-6">
                        <div class="short_contact_list">
                            <ul>
                                <li><a href="#"> <i class="fa fa-envelope"></i> info@medic.com</a></li>
                                <li><a href="#"> <i class="fa fa-phone"></i> 160160</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="sticky-header" class="main-header-area">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-2">
                        <div class="logo">
                            <a href='@Url.Action("Index", "Home")'>
                                <img src="../../img/logo.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-10">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a class="active" href='@Url.Action("Index", "Home")'>Home</a></li>
                                    <li><a href='@Url.Action("Department", "Services")'>Department</a></li>
                                    <li><a href='@Url.Action("Index", "Blog")'>Blog</a></li>
                                    <li><a href='@Url.Action("Index", "AboutUs")'>About</a></li>
                                    <li><a href='@Url.Action("Index", "Doctor")'>Doctors</a></li>
                                    @{
                                        if (User.IsInRole("Admin"))
                                        {
                                            <li><a href='@Url.Action("Index", "Role")'>Role</a></li>
                                        }
                                    }
                                    @Html.Partial("_LoginPartial")
                                    </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

Views/Shared/_footer.cshtml
<footer class="footer">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="footer_widget">
                        <div class="footer_logo">
                            <a href='@Url.Action("Index","Home")'>
                                <img src="../../img/footer_logo.png" alt="">
                            </a>
                        </div>
                        <p>
                            Firmament morning sixth subdue darkness
                            creeping gathered divide.
                        </p>
                        <div class="socail_links">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-xl-2 offset-xl-1 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Departments
                        </h3>
                        <ul>
                            <li><a href="#">Eye Care</a></li>
                            <li><a href="#">Skin Care</a></li>
                            <li><a href="#">Pathology</a></li>
                            <li><a href="#">Medicine</a></li>
                            <li><a href="#">Dental</a></li>
                        </ul>

                    </div>
                </div>
                <div class="col-xl-2 col-md-6 col-lg-2">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Useful Links
                        </h3>
                        <ul>
                            <li><a class="active" href='@Url.Action("Index","Home")'>Home</a></li>
                            <li><a href='@Url.Action("Department","Services")'>Department</a></li>
                            <li><a href='@Url.Action("Index","Blog")'>Blog</a></li>
                            <li><a href='@Url.Action("Index","AboutUs")'>About</a></li>
                            <li><a href='@Url.Action("Index","Doctor")'>Doctors</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Address
                        </h3>
                        <p>
                            200, D-block, Green lane BD <br>
                            +10 367 467 8934 <br>
                            medic@contact.com
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-right_text">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center">                       
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
<form id="test-form" class="white-popup-block mfp-hide">
    <div class="popup_box ">
        <div class="popup_inner">
            <h3>Make an Appointment</h3>
            <form action="#">
                <div class="row">
                    <div class="col-xl-6">
                        <input id="datepicker" placeholder="Pick date">
                    </div>
                    <div class="col-xl-6">
                        <input id="datepicker2" placeholder="Suitable time">
                    </div>
                    <div class="col-xl-6">
                        <select class="form-select wide" id="default-select" class="">
                            <option data-display="Select Department">Department</option>
                            <option value="1">Eye Care</option>
                            <option value="2">Physical Therapy</option>
                            <option value="3">Dental Care</option>
                        </select>
                    </div>
                    <div class="col-xl-6">
                        <select class="form-select wide" id="default-select" class="">
                            <option data-display="Doctors">Doctors</option>
                            <option value="1">Mirazul Alom</option>
                            <option value="2">Monzul Alom</option>
                            <option value="3">Azizul Isalm</option>
                        </select>
                    </div>
                    <div class="col-xl-6">
                        <input type="text" placeholder="Name">
                    </div>
                    <div class="col-xl-6">
                        <input type="text" placeholder="Phone no.">
                    </div>
                    <div class="col-xl-12">
                        <input type="email" placeholder="Email">
                    </div>
                    <div class="col-xl-12">
                        <button type="submit" class="boxed-btn3">Confirm</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</form>